[tools]
node = "22"     # Use same version in .node-version
yarn = "4.10.3" # Use same version in package.json

[tasks.exportTransactions]
description = "Export Paypal transactions to CSV"
env = { NODE_ENV = 'production' }
run = "./scripts/fetchPaypalTransactions.ts"
